import { createElement } from 'lwc';
import ButtonForTestCase from 'c/buttonForTestCase';

describe('c-button-for-test-case', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-button-for-test-case', {
            is: ButtonForTestCase
        });

        // Act
        document.body.appendChild(element);

        // Assert
     const div = element.shadowRoot.querySelector('h1');
        expect(div.textContent).toBe('Hello');
    });
});