import { createElement } from 'lwc';
import SumForTest from 'c/sumForTest';

// 

describe('c-sum-for-test', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-sum-for-test', {
            is: SumForTest
        });

        // Act
        console.log(element.variable)
        document.body.appendChild(element);
//const sum = require('c/sumForTest')
        // Assert
          const value = element.shadowRoot.querySelector('h1');
        
        expect(value.textContent).toBe('5');
        // expect(typeof value.textContent).toBe('string');
        // expect(value.textContent).toBeInstanceOf("String")
        // console.log(element.sum)
    });
});

