import { createElement } from 'lwc';
import JustForTest from 'c/justForTest';

describe('c-just-for-test', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-just-for-test', {
            is: JustForTest
        });

        // Act
        document.body.appendChild(element);

        // Assert
        const h1 = element.shadowRoot.querySelector('h1');
        expect(h1.textContent).toBe("Just for Test! value = Contact");
    });
});